language: python

notifications:
  email: false

python:
    - 3.6
    - 3.7
    - 3.8

# The Travis CI job lifecycle specifies the order of the commands below phases.
# https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

# -------------------- install: install any dependencies required -------------
before_install:
  - uname --all # Print system information
  - python --version # Print python information

install:
  - pip install --upgrade --requirement=requirements.txt
  - pip list # List installed packages
  
# -------------------- script: run the build script ---------------------------
before_script:
  - pip install . # Install the package
  - pip show treedoc # Show information about the package
  - black . -l 120 --check # Check that code is formatted correctly w.r.t. black
  - flake8 treedoc --select=F401 --exclude=__init__.py # Unused imports
  - bash ./linting.sh # Spelling errors
  - mypy treedoc/*.py --ignore-missing-imports --show-error-context # Static type analysis

script:
  # Install the test package before running the tests
  - pip install treedoc/tests
  - pytest treedoc --verbose --doctest-modules --color=yes # Run all tests

# -------------------- deploy: deploy to PyPI if it's a tagged commit ---------
after_script:
  - python setup.py sdist # Source distribution
  - python setup.py bdist_wheel # Binary distribution (not really needed)
  # report any problems rendering your README. If your markup renders fine, 
  # the command will output Checking distribution FILENAME: Passed.
  - twine check dist/*
  
  - if [[ -z "$TRAVIS_PULL_REQUEST_BRANCH" && "$TRAVIS_PULL_REQUEST" == 'false' && "$TRAVIS_BRANCH" == 'master' ]]; then
    pip install twine;
    python -m twine upload dist/* --username tommyod --password $TWINE --skip-existing;
    fi
  - echo "$TRAVIS_TAG"
